includes:
  - config/MAE/base_mae.yaml

dataset_config:
  imnet_pretrain:
    cache_mode: false
    sampler: infinite
    filter_small_patches: false
    imdb_files:
      train:
        image_folder: train
        mask_folder: fh_train
      val:
        image_folder: val
        mask_folder: fh_val
    processors:
      image_train_processor:
        type: compose
        params:
          preprocessors:
            - type: random_resize_crop_w_loop
              params:
                image_size:
                  - 224
                  - 224
                scale:
                  - 0.2
                  - 1.0
                ratio:
                  - 0.75
                  - 1.3333333333333333
                interpolation: 3
            - type: random_horizontal_flip
              params:
                prob: 0.5
            - type: to_tensor
              params: {}
            - type: normalize
              params:
                mean:
                  - 0.485
                  - 0.456
                  - 0.406
                std:
                  - 0.229
                  - 0.224
                  - 0.225
      image_test_processor:
        type: compose
        params:
          preprocessors:
            - type: resize
              params:
                image_size:
                  - 224
                  - 224
                interpolation: 3
            - type: to_tensor
              params: {}
            - type: normalize
              params:
                mean:
                  - 0.485
                  - 0.456
                  - 0.406
                std:
                  - 0.229
                  - 0.224
                  - 0.225

scheduler:
  type: cosine_annealing
  params:
    T_max: ${training.max_update}
    eta_min: 0.0
    use_warmup: true
    warmup_factor: 0.0
    warmup_iterations: 12480

training:
  max_update: 249600