includes:
  - config/RMAE/base_rmae.yaml

dataset_config:
  coco_pretrain:
    sampler: infinite
    mask_type: fh
    filter_small_patches: false
    imdb_files:
      train:
        image_folder:
          - image/train2017
          - image/unlabeled2017
        mask_folder:
          - image/fh_train2017
          - image/fh_unlabeled2017
        anno_file:
          - annotations/instances_train2017.json
          - annotations/image_info_unlabeled2017.json
      val:
        image_folder:
          - image/val2017
        mask_folder:
          - image/fh_val2017
        anno_file:
          - annotations/instances_val2017.json
    processors:
      image_train_processor:
        type: compose
        params:
          preprocessors:
            - type: random_resize_crop_w_loop
              params:
                image_size:
                  - 224
                  - 224
                scale:
                  - 0.2
                  - 1.0
                ratio:
                  - 0.75
                  - 1.3333333333333333
                interpolation: 3
            - type: random_horizontal_flip
              params:
                prob: 0.5
            - type: to_tensor
              params: {}
            - type: normalize
              params:
                mean:
                  - 0.485
                  - 0.456
                  - 0.406
                std:
                  - 0.229
                  - 0.224
                  - 0.225
      image_test_processor:
        type: compose
        params:
          preprocessors:
            - type: resize
              params:
                image_size:
                  - 224
                  - 224
                interpolation: 3
            - type: to_tensor
              params: {}
            - type: normalize
              params:
                mean:
                  - 0.485
                  - 0.456
                  - 0.406
                std:
                  - 0.229
                  - 0.224
                  - 0.225

training:
  run_type: train_val
  evaluation_interval: 50
  checkpoint_interval: 10